theme: jekyll-theme-slate
future: true
title: MelodyBot
description: Senior Project for the Computer Science and Engineering Department of the University of Nevada, Reno Spring 2018
show_downloads: true
